#!/bin/bash

# Insert Detailed Check-In template
wrangler d1 execute mitobyte-users --remote --command "INSERT INTO form_templates (name, form_type, title, description, questions, is_system) VALUES ('Detailed Check-In', 'check-in', 'Event Registration', 'Complete this form to register for the event.', '[{\"id\":\"1\",\"label\":\"Full Name\",\"type\":\"text\",\"required\":true,\"placeholder\":\"John Doe\"},{\"id\":\"2\",\"label\":\"Email Address\",\"type\":\"email\",\"required\":true,\"placeholder\":\"john@example.com\"},{\"id\":\"3\",\"label\":\"Phone Number\",\"type\":\"text\",\"required\":false,\"placeholder\":\"(555) 123-4567\"},{\"id\":\"4\",\"label\":\"Role/Title\",\"type\":\"text\",\"required\":false,\"placeholder\":\"Software Engineer\"},{\"id\":\"5\",\"label\":\"Company/Organization\",\"type\":\"text\",\"required\":false,\"placeholder\":\"Tech Corp\"}]', 1);"

# Insert Professional Check-In template
wrangler d1 execute mitobyte-users --remote --command "INSERT INTO form_templates (name, form_type, title, description, questions, is_system) VALUES ('Professional Check-In', 'check-in', 'Professional Event Check-In', 'Please provide your professional information.', '[{\"id\":\"1\",\"label\":\"Full Name\",\"type\":\"text\",\"required\":true,\"placeholder\":\"John Doe\"},{\"id\":\"2\",\"label\":\"Email Address\",\"type\":\"email\",\"required\":true,\"placeholder\":\"john@example.com\"},{\"id\":\"3\",\"label\":\"LinkedIn Profile\",\"type\":\"text\",\"required\":false,\"placeholder\":\"https://linkedin.com/in/...\"},{\"id\":\"4\",\"label\":\"What are you hoping to learn?\",\"type\":\"textarea\",\"required\":false,\"placeholder\":\"Share your goals for this event...\"}]', 1);"

# Insert Event Feedback template
wrangler d1 execute mitobyte-users --remote --command "INSERT INTO form_templates (name, form_type, title, description, questions, is_system) VALUES ('Event Feedback', 'feedback', 'Event Feedback', 'Help us improve! Please share your thoughts about this event.', '[{\"id\":\"1\",\"label\":\"How would you rate this event?\",\"type\":\"rating\",\"required\":true},{\"id\":\"2\",\"label\":\"What did you enjoy most?\",\"type\":\"textarea\",\"required\":false,\"placeholder\":\"Share what you liked...\"},{\"id\":\"3\",\"label\":\"What could be improved?\",\"type\":\"textarea\",\"required\":false,\"placeholder\":\"Share your suggestions...\"},{\"id\":\"4\",\"label\":\"Would you attend future events?\",\"type\":\"radio\",\"required\":true,\"options\":[\"Definitely\",\"Maybe\",\"No\"]}]', 1);"

# Insert Quick Feedback template
wrangler d1 execute mitobyte-users --remote --command "INSERT INTO form_templates (name, form_type, title, description, questions, is_system) VALUES ('Quick Feedback', 'feedback', 'Quick Feedback', 'Rate your experience in 2 quick questions.', '[{\"id\":\"1\",\"label\":\"Overall Experience\",\"type\":\"rating\",\"required\":true},{\"id\":\"2\",\"label\":\"Comments (Optional)\",\"type\":\"textarea\",\"required\":false,\"placeholder\":\"Any additional thoughts?\"}]', 1);"

# Insert Detailed Feedback template
wrangler d1 execute mitobyte-users --remote --command "INSERT INTO form_templates (name, form_type, title, description, questions, is_system) VALUES ('Detailed Feedback', 'feedback', 'Detailed Event Feedback', 'Your detailed feedback helps us create better events.', '[{\"id\":\"1\",\"label\":\"Overall Rating\",\"type\":\"rating\",\"required\":true},{\"id\":\"2\",\"label\":\"Content Quality\",\"type\":\"rating\",\"required\":true},{\"id\":\"3\",\"label\":\"Venue/Location\",\"type\":\"rating\",\"required\":true},{\"id\":\"4\",\"label\":\"Networking Opportunities\",\"type\":\"rating\",\"required\":true},{\"id\":\"5\",\"label\":\"What worked well?\",\"type\":\"textarea\",\"required\":false,\"placeholder\":\"\"},{\"id\":\"6\",\"label\":\"What needs improvement?\",\"type\":\"textarea\",\"required\":false,\"placeholder\":\"\"},{\"id\":\"7\",\"label\":\"Topics for future events?\",\"type\":\"textarea\",\"required\":false,\"placeholder\":\"\"}]', 1);"

echo "Form templates inserted successfully!"
