/**
 * API Keys Management (Admin Only)
 * Manage API keys for secure access
 */

import { isAdmin } from '../../utils/adminAuth.js'
import { generateApiKey } from '../../utils/apiKeyAuth.js'

export async function onRequestGet({ request, env }) {
  try {
    const url = new URL(request.url)
    const adminEmail = url.searchParams.get('adminEmail')

    // Verify admin
    if (!adminEmail || !isAdmin(adminEmail)) {
      return new Response(
        JSON.stringify({ success: false, error: 'Unauthorized' }),
        { status: 403, headers: { 'Content-Type': 'application/json' } }
      )
    }

    // Get all API keys
    const { results } = await env.DB.prepare(
      `SELECT id, key_name, api_key, created_by, created_at, last_used_at,
              expires_at, is_active, scopes, rate_limit, notes
       FROM api_keys
       ORDER BY created_at DESC`
    ).all()

    // Parse scopes JSON
    const keys = results.map(key => ({
      ...key,
      scopes: key.scopes ? JSON.parse(key.scopes) : []
    }))

    return new Response(
      JSON.stringify({ success: true, keys }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    console.error('Error fetching API keys:', error)
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    )
  }
}

export async function onRequestPost({ request, env }) {
  try {
    const body = await request.json()
    const { adminEmail, action } = body

    // Verify admin
    if (!adminEmail || !isAdmin(adminEmail)) {
      return new Response(
        JSON.stringify({ success: false, error: 'Unauthorized' }),
        { status: 403, headers: { 'Content-Type': 'application/json' } }
      )
    }

    // Generate new API key
    if (action === 'generate') {
      const { keyName, expiresInDays, scopes, rateLimit, notes } = body

      if (!keyName) {
        return new Response(
          JSON.stringify({ success: false, error: 'Key name is required' }),
          { status: 400, headers: { 'Content-Type': 'application/json' } }
        )
      }

      const apiKey = generateApiKey()
      const expiresAt = expiresInDays
        ? new Date(Date.now() + expiresInDays * 24 * 60 * 60 * 1000).toISOString()
        : null

      const result = await env.DB.prepare(
        `INSERT INTO api_keys (key_name, api_key, created_by, expires_at, scopes, rate_limit, notes)
         VALUES (?, ?, ?, ?, ?, ?, ?)`
      ).bind(
        keyName,
        apiKey,
        adminEmail,
        expiresAt,
        scopes ? JSON.stringify(scopes) : null,
        rateLimit || 1000,
        notes || null
      ).run()

      console.log(`[API Keys] Generated by ${adminEmail}: ${keyName}`)

      return new Response(
        JSON.stringify({
          success: true,
          key: {
            id: result.meta.last_row_id,
            name: keyName,
            apiKey: apiKey
          }
        }),
        { status: 201, headers: { 'Content-Type': 'application/json' } }
      )
    }

    // Deactivate API key
    if (action === 'deactivate') {
      const { keyId } = body

      await env.DB.prepare(
        'UPDATE api_keys SET is_active = 0 WHERE id = ?'
      ).bind(keyId).run()

      console.log(`[API Keys] Deactivated by ${adminEmail}: Key ID ${keyId}`)

      return new Response(
        JSON.stringify({ success: true, message: 'API key deactivated' }),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      )
    }

    // Activate API key
    if (action === 'activate') {
      const { keyId } = body

      await env.DB.prepare(
        'UPDATE api_keys SET is_active = 1 WHERE id = ?'
      ).bind(keyId).run()

      console.log(`[API Keys] Activated by ${adminEmail}: Key ID ${keyId}`)

      return new Response(
        JSON.stringify({ success: true, message: 'API key activated' }),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      )
    }

    // Delete API key
    if (action === 'delete') {
      const { keyId } = body

      // Delete usage logs first
      await env.DB.prepare(
        'DELETE FROM api_key_usage WHERE api_key_id = ?'
      ).bind(keyId).run()

      // Delete the key
      await env.DB.prepare(
        'DELETE FROM api_keys WHERE id = ?'
      ).bind(keyId).run()

      console.log(`[API Keys] Deleted by ${adminEmail}: Key ID ${keyId}`)

      return new Response(
        JSON.stringify({ success: true, message: 'API key deleted' }),
        { status: 200, headers: { 'Content-Type': 'application/json' } }
      )
    }

    return new Response(
      JSON.stringify({ success: false, error: 'Invalid action' }),
      { status: 400, headers: { 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    console.error('Error managing API keys:', error)
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    )
  }
}
